language: node_js
node_js:
- node
deploy:
  provider: npm
  email: rileyt@ohsu.edu
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: P2WDhoJENmuGVMU/drikqcu4aKXalrbZ7zzV420/BCqrJJVAKNY4n6awumaNEYvsI02epgp1iMXKyN4IABJxj7gjLlw8EbTby60kbry1H2rPzGOsW7K29sFJWAOqsrC2zO4UzDxmkxa0bcagkjbzr4ZJyBZkmXRKopG2tsKsrdvaSrFbaLum1CYb+Mp7UNbPiRqNgLq/ZxS4A2ZeFfex6GWbLGvAlSNmP0wyfTIroiOfz+ZR/jCiUJMl0ARSHBpoRA7T+OCAC+RYjC/STZlCmlta6Zk4BL1YJjGVT0RmQ9D9uhH+019dDLL7KTWM/N3xwif15TLXJl7EILxQNBtR5voRAMrHumZZtt6p1r45JReUIdijzbuKZJ/BakzVbGPpDgdVYswXy6Wac2HfxOtGPAnwSfyGSI6HOT7hj6L5VW0KchQaXnOyOXDUbUPC2y8nmB0g8dt4uh4j3wC217ylkmLT6JYtubMLT70b7UGJ/dgwm/AnPVpT+aRNjInWNqo2rWSwi8UYOtFT7UZZgl6u+aB6qE2nZbsAam8KCStw1zmalcPRaAFqJ8nimv57FXa26LsAJ5MMLN+wNCzr+p84lbc4rbBFW2GJWX3eaB9tIVsj9wnoEw3TQpCBWoDNp2Hv+W4DCO6ip1OGCXXhflihOvzZ8nevWIu2tDIkNQRLk70=
