language: node_js
node_js:
- node
deploy:
  provider: npm
  email: jona@ohsu.edu
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: hjEkT+sfiR3MzxBerZX8m3BvTaO1mvF58BpeX1z3geUmFJh4Lq+SQVxNTzxETmKKiHs09mifHOFIUMKCTq+2pi8697ozUcg+if+TzeKtJn4qllY1Jd7nmerDifQRzCWvEgN9A4+8R32g9FnL83CX4inPq1SIe5kr5V9nNypak2g0vQRLu3duE/wyz2Nvw+4dVQLxbe69IZfwrsr7YQBXrn9aHll9Jw7pAEm0KrdCXp6kxGrYB5iNvTfYysB4QhFrKINqkY4dXJEJ0JoiP5mcyJUZNnstu8OIdJ42nX+fo9Kijuo2cn1VS+M/N/bWEQ765F/Mb84VjVZ2OmL9DnI1x2c+RwrSazLYmBn4IiAiB1kHcev1qXJFPhfenUEOpgbxw4Jj83QvpF45C6gvRCNa2Gq6PiC0zzaRB/9K+10lDv+5WliM6hpjQAM9TQXSF6j/x8gCZglLLGwBXbr/RxU4YWhzHX0jcpxpzUUYOELqOVVvTn+cytzmshEHUAZItwY/pbn5v3FiQxA4wJrcpT9l2LtwQ7x85MVp3VkiA7UqDO4hQvtgoFmfpBklCCKQ2Dg+zJAM1hwcwCfiQxUVMlS2/8PaaUr+CW4OoDRGINq4fWt3HDGVUJP6INPkf6y2zU9nBduMmdXJs/1t8tFtRMooVP/nAppBzDyKN+sHCZAL2+Y=
