language: node_js
node_js:
- node
deploy:
  provider: npm
  email: rileyt@ohsu.edu
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: eSdOanQP/7lQj2qUBdcofnumnafFwRHYrKFkzn1X9p6xIQfIQfKQNgba9m1qUBt0TnNoJPVBBsRmujrHpJtmUvypUSB41MRyeh5kmIuEkKd3Xa7vX7Pp27C6pBKY6fGMS61Nsc/BerIpHMLh9707ifUL1hxg04EdLMd1o3S8P1zNtuhLLUd9DXmKNrJxkwhdL39SY/Y5zlWEUtRFr2t3id/xM5DP5q0sLfoIgzMQ5ipjyp7I6hurEK+EAw0MYEag0+9ihOwetcgDzGMhdt5QYmnvFYGKj5x+1EvQl3L3O4h07YzHPFkC9gPs6urbDVnuc3vJ5Cj5DjtFXUkddMJoQ06v/LPQbEDqDmfkc1XX1buQ0MHBVSN7/LzSuI4+IVU3EPgYSBQFZH+O1SdWp1NSN8FoPl9LEHqlUwzJVEE5G/U33a16kNN7O2seIasGa3XVDVikEEGkxyxq1g6IHT4kPhxhM3x1RuUPB89aZ1Z+F+S1Br3tV+1aW95mNL1yWgpTIIx3pSZoqumOuNUZIxK5zz9BH6ejel3BMNvb0DS+KiATdZl43Ogo9Mg+EfWc3QdbXiMrlLdSuB+l8VsF+0YQq3itRxa2gKzzpNcV3DX6tNWfjCmHCF3a+Kb9cRXPmTQO9TJRuvXD39fBj3c81m4DoHqa7xznYYAugOzQaFuQgFA=
